### ISSUE TITLE
Is it possible to configure global cspell.json?

### ISSUE THREAD

**Issue by quolpr** [davidmh/cspell.nvim#18]
Hey! Thank you for the great plugin, spell checking was stopping me from moving away from coc. But the problem is that I want to have global cspell.json that will be merging with local cspell.json. And when it shows the suggestion to add a word, I would like to have the option to add to local or to global. Would it be possible to do with the current setup?

**Comment by davidmh** [comment]
Hi @quolpr,

> Would it be possible to do with the current setup?

Not with the current setup, unfortunately. The main problem is the plugin not being aware of more than one configuration file.

I can see a possible solution where we read multiple json config files to be used only as targets in the code actions.

But with null-ls being [officially archived](https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main#archived), I'm not super keen into adding new features to this plugin. Mainly because I no longer use it.

That being said, I'm open to merging pull requests and to give guidance into adding more features.

**Comment by quolpr** [comment]
@davidmh thanks! If you are no longer use it, I am curious, do you have an alternative?

**Comment by davidmh** [comment]
I'm currently trying out nvim-lint, but it doesn't support code actions. I'm not super happy with it, so I might just come back to null-ls and lock myself into nvim 0.9 for now.
